-- 0009_confused_jubilee.sql
-- Auto-generated by Drizzle to sync schema drift.
-- FIXED: All CREATE TYPE wrapped with EXCEPTION guard.
--        All CREATE TABLE changed to CREATE TABLE IF NOT EXISTS.

DO $$ BEGIN CREATE TYPE "public"."asset_status" AS ENUM('ACTIVE', 'INACTIVE', 'DECOMMISSIONED', 'DISPOSED', 'IN_REPAIR', 'STANDBY'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."cost_method" AS ENUM('AVERAGE', 'FIFO', 'STANDARD'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."criticality" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."failure_code_type" AS ENUM('PROBLEM', 'CAUSE', 'REMEDY'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."inventory_tx_type" AS ENUM('ISSUE', 'RETURN', 'TRANSFER', 'RECEIPT', 'ADJUSTMENT', 'CYCLE_COUNT', 'PHYSICAL_INVENTORY'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."item_type" AS ENUM('STOCKED', 'NON_STOCKED', 'SPECIAL_ORDER'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."job_plan_status" AS ENUM('DRAFT', 'ACTIVE', 'INACTIVE'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."location_type" AS ENUM('FUNCTIONAL', 'OPERATING', 'REPAIR', 'SALVAGE'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."meter_type" AS ENUM('GAUGE', 'CONTINUOUS', 'CHARACTERISTIC'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."permit_approval_status" AS ENUM('PENDING', 'APPROVED', 'REJECTED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."permit_checklist_category" AS ENUM('JSA', 'PPE', 'ISOLATION', 'GAS_TEST', 'LOTO', 'GENERAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."permit_status" AS ENUM('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'CLOSED', 'REJECTED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."permit_type" AS ENUM('HOT_WORK', 'CONFINED_SPACE', 'HEIGHT', 'ELECTRICAL', 'EXCAVATION', 'CHEMICAL', 'GENERAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."pm_forecast_status" AS ENUM('PROJECTED', 'GENERATED', 'COMPLETED', 'SKIPPED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."pm_frequency_type" AS ENUM('CALENDAR', 'METER', 'CALENDAR_AND_METER', 'SEASONAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."pm_interval_unit" AS ENUM('HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."pm_status" AS ENUM('ACTIVE', 'INACTIVE', 'DRAFT'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."sr_channel" AS ENUM('WEB', 'MOBILE', 'EMAIL', 'API', 'WALK_IN'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."sr_priority" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."sr_status" AS ENUM('NEW', 'QUEUED', 'IN_PROGRESS', 'CLOSED', 'RESOLVED', 'CONVERTED', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."wo_priority" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."wo_status" AS ENUM('WAPPR', 'APPR', 'INPRG', 'COMP', 'CLOSE', 'HOLD', 'CAN'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."wo_task_status" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE "public"."wo_type" AS ENUM('CM', 'PM', 'EMERGENCY', 'PROJECT', 'STANDING', 'INSPECTION', 'CALIBRATION'); EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "asset_class_attributes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"class_id" uuid NOT NULL,
	"attr_name" text NOT NULL,
	"attr_type" text DEFAULT 'text' NOT NULL,
	"is_required" boolean DEFAULT false NOT NULL,
	"default_value" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "asset_classifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"parent_id" uuid,
	"class_code" text NOT NULL,
	"description" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "asset_meter_readings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"meter_id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"value" numeric(18, 4) NOT NULL,
	"delta" numeric(18, 4),
	"reading_date" timestamp with time zone DEFAULT now() NOT NULL,
	"source" text DEFAULT 'MANUAL',
	"logged_by_user_id" uuid,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "asset_meters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"asset_id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	"unit" text NOT NULL,
	"meter_type" "meter_type" DEFAULT 'CONTINUOUS' NOT NULL,
	"last_reading" numeric(18, 4),
	"last_reading_date" timestamp with time zone,
	"rollover_value" numeric(18, 4),
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "asset_move_history" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"asset_id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"from_location_id" uuid,
	"to_location_id" uuid,
	"moved_at" timestamp with time zone DEFAULT now() NOT NULL,
	"moved_by_user_id" uuid,
	"reason" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "crew_members" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"crew_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" text DEFAULT 'MEMBER',
	"is_primary" boolean DEFAULT false NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "crews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"crew_num" text NOT NULL,
	"name" text NOT NULL,
	"site_id" uuid,
	"lead_user_id" uuid,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "failure_codes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"type" "failure_code_type" NOT NULL,
	"code" text NOT NULL,
	"description" text NOT NULL,
	"parent_id" uuid,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "inventory_balances" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"item_id" uuid NOT NULL,
	"storeroom_id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"qty_on_hand" numeric(14, 4) DEFAULT '0' NOT NULL,
	"qty_reserved" numeric(14, 4) DEFAULT '0' NOT NULL,
	"qty_on_order" numeric(14, 4) DEFAULT '0' NOT NULL,
	"min_qty" numeric(14, 4) DEFAULT '0',
	"max_qty" numeric(14, 4),
	"safety_stock" numeric(14, 4) DEFAULT '0',
	"bin_location" text,
	"avg_cost" numeric(10, 4) DEFAULT '0',
	"cost_method" "cost_method" DEFAULT 'AVERAGE',
	"last_count_date" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "inventory_transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"item_id" uuid NOT NULL,
	"storeroom_id" uuid NOT NULL,
	"tx_type" "inventory_tx_type" NOT NULL,
	"qty" numeric(14, 4) NOT NULL,
	"unit_cost" numeric(10, 4),
	"total_cost" numeric(14, 2),
	"wo_id" uuid,
	"to_storeroom_id" uuid,
	"user_id" uuid,
	"tx_date" timestamp with time zone DEFAULT now() NOT NULL,
	"reference_num" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"item_num" text NOT NULL,
	"description" text NOT NULL,
	"long_description" text,
	"commodity_code" text,
	"unit_of_issue" text DEFAULT 'EA' NOT NULL,
	"manufacturer" text,
	"part_num" text,
	"item_type" "item_type" DEFAULT 'STOCKED' NOT NULL,
	"gl_account" text,
	"is_hazardous" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"custom_data" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "job_plan_labour" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"jp_id" uuid NOT NULL,
	"task_id" uuid,
	"craft" text NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"hours" numeric(8, 2) NOT NULL,
	"rate" numeric(10, 2)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "job_plan_materials" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"jp_id" uuid NOT NULL,
	"task_id" uuid,
	"item_num" text,
	"description" text NOT NULL,
	"quantity" numeric(10, 4) NOT NULL,
	"unit_cost" numeric(10, 2)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "job_plan_safety" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"jp_id" uuid NOT NULL,
	"hazard" text NOT NULL,
	"control" text NOT NULL,
	"ppe" text,
	"sequence" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "job_plan_tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"jp_id" uuid NOT NULL,
	"sequence" integer NOT NULL,
	"description" text NOT NULL,
	"task_type" text DEFAULT 'GENERAL',
	"estimated_hours" numeric(8, 2),
	"instructions" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "job_plan_tools" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"jp_id" uuid NOT NULL,
	"task_id" uuid,
	"tool_description" text NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "job_plans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"jp_num" text NOT NULL,
	"description" text NOT NULL,
	"long_description" text,
	"status" "job_plan_status" DEFAULT 'DRAFT' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"estimated_duration_hours" numeric(8, 2),
	"created_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "organisations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	"code" text NOT NULL,
	"description" text,
	"address" text,
	"gl_account" text,
	"cost_center" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sites" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"org_id" uuid,
	"name" text NOT NULL,
	"site_num" text NOT NULL,
	"description" text,
	"address" text,
	"timezone" text DEFAULT 'UTC',
	"gl_account" text,
	"cost_center" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_class_attributes" ADD CONSTRAINT "asset_class_attributes_class_id_asset_classifications_id_fk" FOREIGN KEY ("class_id") REFERENCES "public"."asset_classifications"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_classifications" ADD CONSTRAINT "asset_classifications_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_meter_readings" ADD CONSTRAINT "asset_meter_readings_meter_id_asset_meters_id_fk" FOREIGN KEY ("meter_id") REFERENCES "public"."asset_meters"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_meter_readings" ADD CONSTRAINT "asset_meter_readings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_meter_readings" ADD CONSTRAINT "asset_meter_readings_logged_by_user_id_users_id_fk" FOREIGN KEY ("logged_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_meters" ADD CONSTRAINT "asset_meters_asset_id_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_meters" ADD CONSTRAINT "asset_meters_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_move_history" ADD CONSTRAINT "asset_move_history_asset_id_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_move_history" ADD CONSTRAINT "asset_move_history_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_move_history" ADD CONSTRAINT "asset_move_history_from_location_id_locations_id_fk" FOREIGN KEY ("from_location_id") REFERENCES "public"."locations"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_move_history" ADD CONSTRAINT "asset_move_history_to_location_id_locations_id_fk" FOREIGN KEY ("to_location_id") REFERENCES "public"."locations"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "asset_move_history" ADD CONSTRAINT "asset_move_history_moved_by_user_id_users_id_fk" FOREIGN KEY ("moved_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "crew_members" ADD CONSTRAINT "crew_members_crew_id_crews_id_fk" FOREIGN KEY ("crew_id") REFERENCES "public"."crews"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "crew_members" ADD CONSTRAINT "crew_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "crews" ADD CONSTRAINT "crews_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "crews" ADD CONSTRAINT "crews_site_id_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "crews" ADD CONSTRAINT "crews_lead_user_id_users_id_fk" FOREIGN KEY ("lead_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "failure_codes" ADD CONSTRAINT "failure_codes_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_balances" ADD CONSTRAINT "inventory_balances_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_balances" ADD CONSTRAINT "inventory_balances_storeroom_id_storerooms_id_fk" FOREIGN KEY ("storeroom_id") REFERENCES "public"."storerooms"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_balances" ADD CONSTRAINT "inventory_balances_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_storeroom_id_storerooms_id_fk" FOREIGN KEY ("storeroom_id") REFERENCES "public"."storerooms"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_wo_id_work_orders_id_fk" FOREIGN KEY ("wo_id") REFERENCES "public"."work_orders"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_to_storeroom_id_storerooms_id_fk" FOREIGN KEY ("to_storeroom_id") REFERENCES "public"."storerooms"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "items" ADD CONSTRAINT "items_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plan_labour" ADD CONSTRAINT "job_plan_labour_jp_id_job_plans_id_fk" FOREIGN KEY ("jp_id") REFERENCES "public"."job_plans"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plan_labour" ADD CONSTRAINT "job_plan_labour_task_id_job_plan_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."job_plan_tasks"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plan_materials" ADD CONSTRAINT "job_plan_materials_jp_id_job_plans_id_fk" FOREIGN KEY ("jp_id") REFERENCES "public"."job_plans"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plan_materials" ADD CONSTRAINT "job_plan_materials_task_id_job_plan_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."job_plan_tasks"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plan_safety" ADD CONSTRAINT "job_plan_safety_jp_id_job_plans_id_fk" FOREIGN KEY ("jp_id") REFERENCES "public"."job_plans"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plan_tasks" ADD CONSTRAINT "job_plan_tasks_jp_id_job_plans_id_fk" FOREIGN KEY ("jp_id") REFERENCES "public"."job_plans"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plan_tools" ADD CONSTRAINT "job_plan_tools_jp_id_job_plans_id_fk" FOREIGN KEY ("jp_id") REFERENCES "public"."job_plans"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plan_tools" ADD CONSTRAINT "job_plan_tools_task_id_job_plan_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."job_plan_tasks"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plans" ADD CONSTRAINT "job_plans_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "job_plans" ADD CONSTRAINT "job_plans_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "organisations" ADD CONSTRAINT "organisations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "sites" ADD CONSTRAINT "sites_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "sites" ADD CONSTRAINT "sites_org_id_organisations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organisations"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "asset_class_tenant_idx" ON "asset_classifications" USING btree ("tenant_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meter_readings_meter_idx" ON "asset_meter_readings" USING btree ("meter_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "asset_meters_asset_idx" ON "asset_meters" USING btree ("asset_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "asset_move_asset_idx" ON "asset_move_history" USING btree ("asset_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "crew_members_crew_idx" ON "crew_members" USING btree ("crew_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "crew_members_unique_idx" ON "crew_members" USING btree ("crew_id","user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "crews_tenant_idx" ON "crews" USING btree ("tenant_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "failure_codes_tenant_type_idx" ON "failure_codes" USING btree ("tenant_id","type");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "inv_balances_item_idx" ON "inventory_balances" USING btree ("item_id","storeroom_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "inv_balances_unique_idx" ON "inventory_balances" USING btree ("item_id","storeroom_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "inv_tx_tenant_idx" ON "inventory_transactions" USING btree ("tenant_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "inv_tx_item_idx" ON "inventory_transactions" USING btree ("item_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "inv_tx_wo_idx" ON "inventory_transactions" USING btree ("wo_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "items_tenant_idx" ON "items" USING btree ("tenant_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "items_num_idx" ON "items" USING btree ("tenant_id","item_num");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "job_plans_tenant_idx" ON "job_plans" USING btree ("tenant_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "job_plans_num_idx" ON "job_plans" USING btree ("tenant_id","jp_num");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "organisations_tenant_idx" ON "organisations" USING btree ("tenant_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sites_tenant_idx" ON "sites" USING btree ("tenant_id");
